// Entity → sub-tab → field schema, sourced from entityTabsConfig.json which
// is generated by scripts/parseExcel.js from REST APIs.xlsx.
// Do NOT hardcode tab arrays here — edit entityTabsConfig.json or re-run the
// parser script to update the schema.

import entityTabsConfig from './entityTabsConfig.json'

export const DEFAULT_SUB_TABS = [
  { tabId: 'general', tabName: 'General', fields: [] }
]

export function getEntitySubTabs(entityId) {
  const tabs = entityTabsConfig[entityId]
  return tabs && tabs.length ? tabs : DEFAULT_SUB_TABS
}
